# Generated by Django 4.2.6 on 2024-01-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
