# Generated by Django 4.2.6 on 2024-01-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_category',
            options={},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.product_category')),
            ],
            options={
                'verbose_name': 'Types',
                'verbose_name_plural': 'Types',
            },
        ),
    ]
